class PortfolioModel {
  final String portfolioId;
  final String freelancerId;
  final String projectTitle;
  final String? projectDescription;
  final String? projectUrl;
  final DateTime? completionDate;
  final bool isAutoGenerated;
  final String? contractId;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  const PortfolioModel({
    required this.portfolioId,
    required this.freelancerId,
    required this.projectTitle,
    this.projectDescription,
    this.projectUrl,
    this.completionDate,
    this.isAutoGenerated = false,
    this.contractId,
    this.createdAt,
    this.updatedAt,
  });

  factory PortfolioModel.fromJson(Map<String, dynamic> json) {
    return PortfolioModel(
      portfolioId: (json['portfolio_id'] ?? '').toString(),
      freelancerId: (json['freelancer_id'] ?? '').toString(),
      projectTitle: (json['project_title'] ?? '').toString(),
      projectDescription: json['project_description']?.toString(),
      projectUrl: json['project_url']?.toString(),
      completionDate: json['completion_date'] != null
          ? DateTime.tryParse(json['completion_date'].toString())
          : null,
      isAutoGenerated: json['is_auto_generated'] as bool? ?? false,
      contractId: json['contract_id']?.toString(),
      createdAt: json['created_at'] != null
          ? DateTime.tryParse(json['created_at'].toString())
          : null,
      updatedAt: json['updated_at'] != null
          ? DateTime.tryParse(json['updated_at'].toString())
          : null,
    );
  }

  Map<String, dynamic> toMap() => {
    'portfolio_id': portfolioId,
    'freelancer_id': freelancerId,
    'project_title': projectTitle,
    'project_description': projectDescription,
    'project_url': projectUrl,
    'completion_date': completionDate?.toIso8601String(),
    'is_auto_generated': isAutoGenerated,
    'contract_id': contractId,
    'created_at': createdAt?.toIso8601String(),
    'updated_at': updatedAt?.toIso8601String(),
  };
}
