class PortfolioModel {
  final String portfolioId;
  final String freelancerId;
  final String projectTitle;
  final String? projectDescription;
  final String? projectUrl;
  final DateTime? completionDate;
  final bool isAutoGenerated;
  final String? contractId;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  /// 'scanning' | 'visible' | 'blocked' - see portfolio_functions.py's
  /// run_portfolio_scan(). Defaults to 'visible' when absent so entries that
  /// predate this field (or come from a stripped-down response) don't get
  /// mistaken for pending/blocked.
  final String moderationStatus;

  /// Raw label keys (e.g. 'toxic', 'insult') from the backend's `detected_labels`
  /// JSONB column - see harmful_text.md section 17. Empty unless moderationStatus
  /// is 'blocked'. Not human-readable; map via labelDisplayName() before showing.
  final List<String> detectedLabels;

  const PortfolioModel({
    required this.portfolioId,
    required this.freelancerId,
    required this.projectTitle,
    this.projectDescription,
    this.projectUrl,
    this.completionDate,
    this.isAutoGenerated = false,
    this.contractId,
    this.createdAt,
    this.updatedAt,
    this.moderationStatus = 'visible',
    this.detectedLabels = const [],
  });

  factory PortfolioModel.fromJson(Map<String, dynamic> json) {
    return PortfolioModel(
      portfolioId: (json['portfolio_id'] ?? '').toString(),
      freelancerId: (json['freelancer_id'] ?? '').toString(),
      projectTitle: (json['project_title'] ?? '').toString(),
      projectDescription: json['project_description']?.toString(),
      projectUrl: json['project_url']?.toString(),
      completionDate: json['completion_date'] != null
          ? DateTime.tryParse(json['completion_date'].toString())
          : null,
      isAutoGenerated: json['is_auto_generated'] as bool? ?? false,
      contractId: json['contract_id']?.toString(),
      createdAt: json['created_at'] != null
          ? DateTime.tryParse(json['created_at'].toString())
          : null,
      updatedAt: json['updated_at'] != null
          ? DateTime.tryParse(json['updated_at'].toString())
          : null,
      moderationStatus: json['moderation_status'] as String? ?? 'visible',
      detectedLabels: (json['detected_labels'] as List?)
              ?.map((e) => e.toString())
              .toList() ??
          const [],
    );
  }

  Map<String, dynamic> toMap() => {
    'portfolio_id': portfolioId,
    'freelancer_id': freelancerId,
    'project_title': projectTitle,
    'project_description': projectDescription,
    'project_url': projectUrl,
    'completion_date': completionDate?.toIso8601String(),
    'is_auto_generated': isAutoGenerated,
    'contract_id': contractId,
    'created_at': createdAt?.toIso8601String(),
    'updated_at': updatedAt?.toIso8601String(),
  };
}
